package rest.web.controller;

import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import rest.application.exception.ExcelParserException;
import rest.application.exception.ImportException;
import rest.service.ImportService;

@RestController
@RequestMapping(value = "/import/")
public class ImportController {

    @Autowired
    private ImportService importService;

    @ApiOperation(value = "Import data represented as JSON",
                notes = "Method to import data chunks that are represented in a JSON format. Make sure that the JSON format does correspond to the VisMo JSON Schema!")
    @PostMapping
    public ResponseEntity importJSON(
            @RequestBody String json) throws ImportException {
        this.importService.importJSON(json);

        return new ResponseEntity(HttpStatus.NO_CONTENT);
    }

    @ApiOperation(value = "Import data represented in an Excel File",
                notes = "Method to import data contained in an Excel File. This Excel File must follow the structure generated by the Excel File generation of this project.")
    @PostMapping(value = "excel")
    public ResponseEntity importExcelUpload(
            @RequestParam MultipartFile file) throws ExcelParserException {
        this.importService.importExcelUpload(file);

        return new ResponseEntity(HttpStatus.NO_CONTENT);
    }
}
